version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/my-app:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true